#!/usr/bin/node

var util = require('util');
var root = __dirname;

var spawn = require('child_process').spawn;
var child = spawn('node', [root + '/test/fixtures/server.js']);

require.paths.push(__dirname);
require.paths.push(__dirname + '/lib');
var testrunner = require('nodeunit').reporters.default;

process.chdir(__dirname);

testrunner.run(['test/rpc', 'test']);

